import { Router } from 'express';
import { registerRoute } from '../helpers/controller-wrapper.js';
import createRoute from '../app/projects/create/route.js';
import listRoute from '../app/projects/list/route.js';
import viewRoute from '../app/projects/view/route.js';
import updateRoute from '../app/projects/update/route.js';
import deleteRoute from '../app/projects/delete/route.js';
import assignmentsAddRoute from '../app/projects/assignments/add/route.js';
import assignmentsRemoveRoute from '../app/projects/assignments/remove/route.js';
import assignmentsListRoute from '../app/projects/assignments/list/route.js';
import treeCreateRoute from '../app/projects/tree/create/route.js';
import treeListRoute from '../app/projects/tree/list/route.js';
import treeBreadcrumbRoute from '../app/projects/tree/breadcrumb/route.js';
import treeMoveRoute from '../app/projects/tree/move/route.js';
import treeReorderRoute from '../app/projects/tree/reorder/route.js';
import treeDeleteRoute from '../app/projects/tree/delete/route.js';
import treeFullRoute from '../app/projects/tree/full/route.js';
import treeNodeDetailRoute from '../app/projects/tree/node-detail/route.js';
import pfSectionsCreateRoute from '../app/projects/permanent-file/sections/create/route.js';
import pfSectionsListRoute from '../app/projects/permanent-file/sections/list/route.js';
import pfSectionsViewRoute from '../app/projects/permanent-file/sections/view/route.js';
import pfSectionsUpdateRoute from '../app/projects/permanent-file/sections/update/route.js';
import pfSectionsDeleteRoute from '../app/projects/permanent-file/sections/delete/route.js';
import pfItemsCreateRoute from '../app/projects/permanent-file/items/create/route.js';
import pfItemsListRoute from '../app/projects/permanent-file/items/list/route.js';
import pfItemsUpdateRoute from '../app/projects/permanent-file/items/update/route.js';
import pfItemsDeleteRoute from '../app/projects/permanent-file/items/delete/route.js';
import pfItemsDocumentsListRoute from '../app/projects/permanent-file/items/documents-list/route.js';
import pfApplyTemplateRoute from '../app/projects/permanent-file/apply-template/route.js';

const router = Router();

registerRoute(router, '/create', createRoute, 'post');
registerRoute(router, '/list', listRoute, 'post');
registerRoute(router, '/view', viewRoute, 'post');
registerRoute(router, '/update', updateRoute, 'post');
registerRoute(router, '/delete', deleteRoute, 'post');
registerRoute(router, '/assignments/add', assignmentsAddRoute, 'post');
registerRoute(router, '/assignments/remove', assignmentsRemoveRoute, 'post');
registerRoute(router, '/assignments/list', assignmentsListRoute, 'post');
registerRoute(router, '/tree/create', treeCreateRoute, 'post');
registerRoute(router, '/tree/list', treeListRoute, 'post');
registerRoute(router, '/tree/breadcrumb', treeBreadcrumbRoute, 'post');
registerRoute(router, '/tree/move', treeMoveRoute, 'post');
registerRoute(router, '/tree/reorder', treeReorderRoute, 'post');
registerRoute(router, '/tree/delete', treeDeleteRoute, 'post');
registerRoute(router, '/tree/full', treeFullRoute, 'post');
registerRoute(router, '/tree/node-detail', treeNodeDetailRoute, 'post');
registerRoute(router, '/permanent-file/sections/create', pfSectionsCreateRoute, 'post');
registerRoute(router, '/permanent-file/sections/list', pfSectionsListRoute, 'post');
registerRoute(router, '/permanent-file/sections/view', pfSectionsViewRoute, 'post');
registerRoute(router, '/permanent-file/sections/update', pfSectionsUpdateRoute, 'post');
registerRoute(router, '/permanent-file/sections/delete', pfSectionsDeleteRoute, 'post');
registerRoute(router, '/permanent-file/items/create', pfItemsCreateRoute, 'post');
registerRoute(router, '/permanent-file/items/list', pfItemsListRoute, 'post');
registerRoute(router, '/permanent-file/items/update', pfItemsUpdateRoute, 'post');
registerRoute(router, '/permanent-file/items/delete', pfItemsDeleteRoute, 'post');
registerRoute(router, '/permanent-file/items/documents/list', pfItemsDocumentsListRoute, 'post');
registerRoute(router, '/permanent-file/apply-template', pfApplyTemplateRoute, 'post');

export default router;
