/**
 * InventoryBatch: lote de producto para trazabilidad de costos y fechas.
 * Toda entrada genera obligatoriamente un lote (aunque sea "S/N").
 */
export default function (sequelize, DataTypes) {
  const InventoryBatch = sequelize.define(
    'InventoryBatch',
    {
      id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true
      },
      productId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        field: 'product_id'
      },
      establishmentId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        field: 'establishment_id'
      },
      batchCode: {
        type: DataTypes.STRING(100),
        allowNull: false,
        defaultValue: 'S/N',
        field: 'batch_code'
      },
      manufacturingDate: {
        type: DataTypes.DATEONLY,
        allowNull: true,
        field: 'manufacturing_date'
      },
      expirationDate: {
        type: DataTypes.DATEONLY,
        allowNull: false,
        field: 'expiration_date'
      },
      registrationDate: {
        type: DataTypes.DATE,
        allowNull: false,
        field: 'registration_date'
      },
      unitCost: {
        type: DataTypes.DECIMAL(12, 4),
        allowNull: false,
        defaultValue: 0.0000,
        field: 'unit_cost'
      },
      initialQuantity: {
        type: DataTypes.DECIMAL(12, 4),
        allowNull: false,
        defaultValue: 0.0000,
        field: 'initial_quantity'
      },
      currentQuantity: {
        type: DataTypes.DECIMAL(12, 4),
        allowNull: false,
        defaultValue: 0.0000,
        field: 'current_quantity'
      },
      autoGenerated: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: true,
        field: 'auto_generated',
        comment: 'false = lote creado por el usuario; true = generado automáticamente por el sistema'
      },
      createdAt: {
        type: DataTypes.DATE,
        field: 'created_at'
      },
      updatedAt: {
        type: DataTypes.DATE,
        field: 'updated_at'
      },
      deletedAt: {
        type: DataTypes.DATE,
        allowNull: true,
        field: 'deleted_at'
      }
    },
    {
      tableName: 'inventory_batches',
      paranoid: true,
      timestamps: true,
      underscored: true,
      indexes: [
        { fields: ['product_id', 'establishment_id'], name: 'inventory_batches_product_establishment' },
        { fields: ['expiration_date'], name: 'inventory_batches_expiration_date' }
      ]
    }
  );

  /**
   * Genera fecha de vencimiento por defecto: +10 años desde hoy.
   */
  InventoryBatch.getDefaultExpirationDate = function () {
    const d = new Date();
    d.setFullYear(d.getFullYear() + 10);
    return d;
  };

  /**
   * Obtiene o crea un lote para entrada. Si batchId se proporciona y existe, retorna ese lote.
   * Si no, crea uno nuevo con batchCode='S/N' y expirationDate +10 años.
   */
  InventoryBatch.getOrCreateForEntry = async function (params, transaction = null) {
    const { productId, establishmentId, batchId, batchCode, manufacturingDate, expirationDate, unitCost: unitCostParam, quantity } = params;
    const options = transaction ? { transaction } : {};
    const now = new Date();
    const defaultExp = InventoryBatch.getDefaultExpirationDate();

    if (batchId) {
      const batch = await InventoryBatch.findByPk(batchId, options);
      if (batch && batch.productId === productId && batch.establishmentId === establishmentId) {
        return batch;
      }
    }

    const hasUserBatchData = (batchCode && batchCode.trim() !== 'S/N') || manufacturingDate || expirationDate;
    const newBatch = await InventoryBatch.create(
      {
        productId,
        establishmentId,
        batchCode: batchCode || 'S/N',
        manufacturingDate: manufacturingDate || null,
        expirationDate: expirationDate || defaultExp.toISOString().slice(0, 10),
        registrationDate: now,
        unitCost: unitCostParam != null ? parseFloat(unitCostParam) : 0,
        initialQuantity: quantity,
        currentQuantity: quantity,
        autoGenerated: !hasUserBatchData
      },
      options
    );
    return newBatch;
  };

  /**
   * Obtiene lotes con stock disponibles ordenados FEFO (First Expired, First Out).
   */
  InventoryBatch.findAvailableByFEFO = async function (productId, establishmentId, transaction = null) {
    const { Op } = require('sequelize');
    const options = transaction ? { transaction } : {};
    return InventoryBatch.findAll({
      where: {
        productId,
        establishmentId,
        currentQuantity: { [Op.gt]: 0 }
      },
      order: [['expirationDate', 'ASC']],
      ...options
    });
  };

  /**
   * Recalcula y actualiza inventory_stock.current_stock para un producto en un establecimiento.
   */
  InventoryBatch.syncInventoryStock = async function (productId, establishmentId, transaction = null) {
    const { InventoryStock } = sequelize.models;
    const options = transaction ? { transaction } : {};
    const result = await InventoryBatch.findAll({
      where: { productId, establishmentId },
      attributes: [[sequelize.fn('SUM', sequelize.col('current_quantity')), 'total']],
      raw: true,
      ...options
    });
    const total = parseFloat(result[0]?.total ?? 0) || 0;

    const stock = await InventoryStock.findOne({
      where: { productId, establishmentId },
      ...options
    });
    const payload = { currentStock: total, updatedAt: new Date() };
    if (stock) {
      await stock.update(payload, options);
    } else {
      await InventoryStock.create(
        { productId, establishmentId, currentStock: total, minStockLevel: 0, updatedAt: new Date() },
        options
      );
    }
  };

  InventoryBatch.associate = function (models) {
    InventoryBatch.belongsTo(models.InventoryProduct, { foreignKey: 'product_id', as: 'product' });
    InventoryBatch.belongsTo(models.Establishment, { foreignKey: 'establishment_id', as: 'establishment' });
  };

  return InventoryBatch;
}
