export default function (sequelize, DataTypes) {
  const InventoryStock = sequelize.define(
    'InventoryStock',
    {
      id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true
      },
      establishmentId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        field: 'establishment_id'
      },
      productId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        field: 'product_id'
      },
      currentStock: {
        type: DataTypes.DECIMAL(12, 4),
        allowNull: false,
        defaultValue: 0.0000,
        field: 'current_stock'
      },
      minStockLevel: {
        type: DataTypes.DECIMAL(12, 4),
        allowNull: true,
        defaultValue: 0.0000,
        field: 'min_stock_level'
      },
      price: {
        type: DataTypes.DECIMAL(12, 4),
        allowNull: true,
        field: 'price',
        comment: 'Precio del producto en este establecimiento (suele coincidir con precio general al crear)'
      },
      updatedAt: {
        type: DataTypes.DATE,
        field: 'updated_at'
      }
    },
    {
      tableName: 'inventory_stock',
      paranoid: false,
      timestamps: false,
      underscored: true,
      indexes: [
        {
          unique: true,
          fields: ['establishment_id', 'product_id'],
          name: 'est_prod_unique'
        }
      ]
    }
  );

  /**
   * Procesa entrada: crea uno o más lotes (según item.batches o lote único), crea UN kardex con batchDetail, sincroniza inventory_stock.
   * Si stockParams.batches es un array, se crea un lote por cada elemento; si no, se usa batchId/lote único como antes.
   */
  async function processEntry(stockParams, userId, movementId, transaction) {
    const { establishmentId, productId, quantity, previousStock, currentStock, minStockLevel, reason, metadata, batchId, unitCost, batchCode, manufacturingDate, expirationDate, costPriceOverride, dateAt, batches: batchesInput } = stockParams;
    const { Kardex, InventoryBatch } = sequelize.models;

    let batchDetail = [];
    let entryCostPrice = 0;

    if (batchesInput && Array.isArray(batchesInput) && batchesInput.length > 0) {
      let totalCost = 0;
      const totalQty = parseFloat(quantity);
      for (const b of batchesInput) {
        const qty = parseFloat(b.quantity);
        const batchId = b.batchId != null ? parseInt(b.batchId, 10) : null;
        const batch = await InventoryBatch.getOrCreateForEntry(
          {
            productId,
            establishmentId,
            batchId,
            batchCode: b.batchCode || 'S/N',
            manufacturingDate: b.manufacturingDate || null,
            expirationDate: b.expirationDate || null,
            unitCost: b.unitCost ?? 0,
            quantity: qty
          },
          transaction
        );
        batchDetail.push({ batchId: batch.id, batchCode: batch.batchCode, quantity: qty, autoGenerated: !!batch.autoGenerated });
        totalCost += qty * parseFloat(batch.unitCost ?? 0);
      }
      entryCostPrice = totalQty > 0 ? totalCost / totalQty : 0;
    } else {
      let batch;
      if (batchId) {
        batch = await InventoryBatch.findByPk(batchId, { transaction });
        if (batch && batch.productId === productId && batch.establishmentId === establishmentId) {
          const qty = parseFloat(quantity);
          await batch.update({ currentQuantity: parseFloat(batch.currentQuantity) + qty, updatedAt: new Date() }, { transaction });
        } else {
          batch = null;
        }
      }
      if (!batch) {
        batch = await InventoryBatch.getOrCreateForEntry(
          {
            productId,
            establishmentId,
            batchCode: batchCode || 'S/N',
            manufacturingDate: manufacturingDate || null,
            expirationDate: expirationDate || null,
            unitCost: unitCost ?? 0,
            quantity: parseFloat(quantity)
          },
          transaction
        );
      }
      batchDetail = [{ batchId: batch.id, batchCode: batch.batchCode, quantity: parseFloat(quantity), autoGenerated: !!batch.autoGenerated }];
      entryCostPrice = costPriceOverride != null ? parseFloat(costPriceOverride) : parseFloat(batch.unitCost ?? 0);
    }

    await Kardex.create(
      {
        establishmentId,
        productId,
        batchDetail,
        costPrice: entryCostPrice,
        dateAt: dateAt || null,
        userId,
        movementId: movementId || null,
        type: 'entry',
        quantity: parseFloat(quantity),
        previousStock,
        newStock: currentStock,
        reason: reason || null,
        metadata: metadata || null,
        isCurrent: true,
        isReversal: false,
        createdAt: new Date()
      },
      { transaction }
    );

    await InventoryBatch.syncInventoryStock(productId, establishmentId, transaction);

    const stockRow = await InventoryStock.findOne({ where: { establishmentId, productId }, transaction });
    if (minStockLevel !== undefined && stockRow) {
      await stockRow.update({ minStockLevel, updatedAt: new Date() }, { transaction });
    }
    return stockRow || await InventoryStock.findOne({ where: { establishmentId, productId }, transaction });
  }

  /**
   * Procesa salida: por defecto FEFO; si batchId viene, se descuenta solo de ese lote; si batches (array de { batchId, quantity }) viene, se descuenta de cada lote indicado.
   * Crea UN kardex con batchDetail (array de lotes usados).
   */
  async function processExit(stockParams, userId, movementId, transaction) {
    const { establishmentId, productId, quantity, previousStock, currentStock, minStockLevel, reason, metadata, dateAt, batchId, batches: batchesInput } = stockParams;
    const { Kardex, InventoryBatch, InventoryProduct } = sequelize.models;

    const product = await InventoryProduct.findByPk(productId, { attributes: ['costPrice'], transaction });
    const exitCostPrice = product ? parseFloat(product.costPrice ?? 0) : 0;

    const qtyRequested = parseFloat(quantity);
    let batchDetail = [];

    if (batchesInput && Array.isArray(batchesInput) && batchesInput.length > 0) {
      for (const b of batchesInput) {
        const batchIdVal = b.batchId != null ? parseInt(b.batchId, 10) : null;
        const qty = parseFloat(b.quantity);
        if (batchIdVal == null || Number.isNaN(qty) || qty <= 0) continue;
        const batch = await InventoryBatch.findByPk(batchIdVal, { transaction });
        if (!batch || batch.productId !== productId || batch.establishmentId !== establishmentId) {
          const err = new Error('inventory.batches.notFound');
          err.code = 'inventory.batches.notFound';
          err.status = 404;
          throw err;
        }
        const available = parseFloat(batch.currentQuantity);
        if (available < qty) {
          const err = new Error('inventory.stock.insufficientStock');
          err.code = 'inventory.stock.insufficientStock';
          err.status = 400;
          throw err;
        }
        const newBatchQty = available - qty;
        await batch.update({ currentQuantity: newBatchQty, updatedAt: new Date() }, { transaction });
        batchDetail.push({ batchId: batch.id, batchCode: batch.batchCode, quantity: qty, autoGenerated: !!batch.autoGenerated });
      }
    } else if (batchId) {
      const batch = await InventoryBatch.findByPk(batchId, { transaction });
      if (!batch || batch.productId !== productId || batch.establishmentId !== establishmentId) {
        const err = new Error('inventory.batches.notFound');
        err.code = 'inventory.batches.notFound';
        err.status = 404;
        throw err;
      }
      const available = parseFloat(batch.currentQuantity);
      if (available < qtyRequested) {
        const err = new Error('inventory.stock.insufficientStock');
        err.code = 'inventory.stock.insufficientStock';
        err.status = 400;
        throw err;
      }
      const newBatchQty = available - qtyRequested;
      await batch.update({ currentQuantity: newBatchQty, updatedAt: new Date() }, { transaction });
      batchDetail = [{ batchId: batch.id, batchCode: batch.batchCode, quantity: qtyRequested, autoGenerated: !!batch.autoGenerated }];
    } else {
      const batches = await InventoryBatch.findAvailableByFEFO(productId, establishmentId, transaction);
      let remaining = qtyRequested;

      for (const batch of batches) {
        if (remaining <= 0) break;
        const available = parseFloat(batch.currentQuantity);
        if (available <= 0) continue;
        const deduct = Math.min(remaining, available);
        const newBatchQty = available - deduct;
        await batch.update({ currentQuantity: newBatchQty, updatedAt: new Date() }, { transaction });
        batchDetail.push({ batchId: batch.id, batchCode: batch.batchCode, quantity: deduct, autoGenerated: !!batch.autoGenerated });
        remaining -= deduct;
      }

      if (remaining > 0) {
        const err = new Error('inventory.stock.insufficientStock');
        err.code = 'inventory.stock.insufficientStock';
        err.status = 400;
        throw err;
      }
    }

    await Kardex.create(
      {
        establishmentId,
        productId,
        batchDetail,
        costPrice: exitCostPrice,
        dateAt: dateAt || null,
        userId,
        movementId: movementId || null,
        type: 'exit',
        quantity: parseFloat(quantity),
        previousStock,
        newStock: currentStock,
        reason: reason || null,
        metadata: metadata || null,
        isCurrent: true,
        isReversal: false,
        createdAt: new Date()
      },
      { transaction }
    );

    await InventoryBatch.syncInventoryStock(productId, establishmentId, transaction);

    const stockRow = await InventoryStock.findOne({ where: { establishmentId, productId }, transaction });
    if (minStockLevel !== undefined && stockRow) {
      await stockRow.update({ minStockLevel, updatedAt: new Date() }, { transaction });
    }
    return stockRow || await InventoryStock.findOne({ where: { establishmentId, productId }, transaction });
  }

  /**
   * Applies one stock change: updates batches, creates kardex record(s), syncs inventory_stock.
   * Entry: creates batch or adds to existing. Exit: FEFO. Transfer: FEFO origin + entry destination.
   */
  InventoryStock.updateStock = async function (stockParams, userId, movementId = null, existingTransaction = null) {
    const { establishmentId, productId, currentStock, minStockLevel, type, quantity, previousStock, reason, metadata, targetEstablishmentId, batchId, unitCost, batchCode, manufacturingDate, expirationDate } = stockParams;
    const { Kardex, InventoryBatch } = sequelize.models;

    const runInTransaction = async (transaction) => {
      const baseMetadata = type === 'transfer' && targetEstablishmentId
        ? { ...metadata, targetEstablishmentId, transferType: 'transfer' }
        : metadata;

      if (type === 'entry') {
        return await processEntry(
          { ...stockParams, metadata: baseMetadata },
          userId,
          movementId,
          transaction
        );
      }

      if (type === 'exit') {
        return await processExit(
          { ...stockParams, metadata: baseMetadata },
          userId,
          movementId,
          transaction
        );
      }

      if (type === 'transfer' && targetEstablishmentId) {
        await processExit(
          { ...stockParams, metadata: baseMetadata },
          userId,
          movementId,
          transaction
        );

        const targetPrevious = await InventoryStock.findOne({
          where: { establishmentId: targetEstablishmentId, productId },
          transaction
        }).then((s) => (s ? parseFloat(s.currentStock) : 0));
        const qty = parseFloat(quantity);
        const targetNew = targetPrevious + qty;

        const { InventoryProduct: InvProduct } = sequelize.models;
        const transferProduct = await InvProduct.findByPk(productId, { attributes: ['costPrice'], transaction });
        const transferCostPrice = transferProduct ? parseFloat(transferProduct.costPrice ?? 0) : 0;

        const destParams = {
          establishmentId: targetEstablishmentId,
          productId,
          quantity: qty,
          previousStock: targetPrevious,
          currentStock: targetNew,
          minStockLevel: targetEstablishmentId ? undefined : minStockLevel,
          reason: reason ? `Recepción: ${reason}` : 'Transferencia recibida',
          metadata: { ...metadata, sourceEstablishmentId: establishmentId, transferType: 'transfer' },
          batchId: null,
          unitCost: transferCostPrice,
          batchCode: 'S/N',
          manufacturingDate: null,
          expirationDate: null,
          costPriceOverride: transferCostPrice,
          dateAt: stockParams.dateAt
        };
        await processEntry(
          { ...destParams },
          userId,
          movementId,
          transaction
        );

        const targetStockRow = await InventoryStock.findOne({
          where: { establishmentId: targetEstablishmentId, productId },
          transaction
        });
        return targetStockRow;
      }

      if (type === 'adjustment') {
        const delta = parseFloat(currentStock) - parseFloat(previousStock);
        if (delta > 0) {
          return await processEntry(
            {
              ...stockParams,
              quantity: delta,
              currentStock: parseFloat(currentStock),
              previousStock: parseFloat(previousStock),
              metadata: baseMetadata
            },
            userId,
            movementId,
            transaction
          );
        }
        if (delta < 0) {
          return await processExit(
            {
              ...stockParams,
              quantity: Math.abs(delta),
              currentStock: parseFloat(currentStock),
              previousStock: parseFloat(previousStock),
              metadata: baseMetadata
            },
            userId,
            movementId,
            transaction
          );
        }

        const stockRow = await InventoryStock.findOne({ where: { establishmentId, productId }, transaction });
        if (stockRow && minStockLevel !== undefined) {
          await stockRow.update({ minStockLevel, updatedAt: new Date() }, { transaction });
        }
        return stockRow;
      }

      const existingStock = await InventoryStock.findOne({
        where: { establishmentId, productId },
        transaction
      });
      const stockData = {
        establishmentId,
        productId,
        currentStock: parseFloat(currentStock),
        minStockLevel: minStockLevel ?? (existingStock?.minStockLevel ?? 0),
        updatedAt: new Date()
      };
      if (existingStock) {
        await existingStock.update(stockData, { transaction });
      } else {
        await InventoryStock.create(stockData, { transaction });
      }
      const { InventoryProduct: InvProductFallback } = sequelize.models;
      const fallbackProduct = await InvProductFallback.findByPk(productId, { attributes: ['costPrice'], transaction });
      const fallbackCostPrice = fallbackProduct ? parseFloat(fallbackProduct.costPrice ?? 0) : 0;

      await Kardex.create(
        {
          establishmentId,
          productId,
          batchDetail: null,
          costPrice: fallbackCostPrice,
          dateAt: stockParams.dateAt || null,
          userId,
          movementId: movementId || null,
          type,
          quantity: parseFloat(quantity),
          previousStock: parseFloat(previousStock),
          newStock: parseFloat(currentStock),
          reason: reason || null,
          metadata: baseMetadata || null,
          isCurrent: true,
          isReversal: false,
          createdAt: new Date()
        },
        { transaction }
      );
      return await InventoryStock.findOne({ where: { establishmentId, productId }, transaction });
    };

    if (existingTransaction) {
      return await runInTransaction(existingTransaction);
    }
    return await sequelize.transaction(runInTransaction);
  };

  InventoryStock.associate = function (models) {
    InventoryStock.belongsTo(models.Establishment, {
      foreignKey: 'establishment_id',
      as: 'establishment'
    });
    InventoryStock.belongsTo(models.InventoryProduct, {
      foreignKey: 'product_id',
      as: 'product'
    });
  };

  return InventoryStock;
}
