export default function (sequelize, DataTypes) {
  const Kardex = sequelize.define(
    'Kardex',
    {
      id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true
      },
      establishmentId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        field: 'establishment_id'
      },
      productId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        field: 'product_id'
      },
      batchDetail: {
        type: DataTypes.JSON,
        allowNull: true,
        field: 'batch_detail',
        get() {
          const val = this.getDataValue('batchDetail');
          let arr = [];
          if (val == null) arr = [];
          else if (Array.isArray(val)) arr = val;
          else if (typeof val === 'string') {
            try {
              const parsed = JSON.parse(val);
              arr = Array.isArray(parsed) ? parsed : [];
            } catch {
              arr = [];
            }
          }
          if (arr.length === 1 && arr[0]?.autoGenerated) return [];
          return arr;
        }
      },
      userId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        field: 'user_id'
      },
      movementId: {
        type: DataTypes.INTEGER,
        allowNull: true,
        field: 'movement_id'
      },
      type: {
        type: DataTypes.ENUM('entry', 'exit', 'transfer', 'adjustment'),
        allowNull: false
      },
      quantity: {
        type: DataTypes.DECIMAL(12, 4),
        allowNull: false
      },
      costPrice: {
        type: DataTypes.DECIMAL(12, 4),
        allowNull: true,
        field: 'cost_price',
        comment: 'Precio costo: en entrada = costo del lote (input); en transferencia/salida = costo por defecto del producto'
      },
      previousStock: {
        type: DataTypes.DECIMAL(12, 4),
        allowNull: false,
        field: 'previous_stock'
      },
      newStock: {
        type: DataTypes.DECIMAL(12, 4),
        allowNull: false,
        field: 'new_stock'
      },
      reason: {
        type: DataTypes.STRING(255),
        allowNull: true
      },
      metadata: {
        type: DataTypes.JSON,
        allowNull: true
      },
      isCurrent: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: true,
        field: 'is_current'
      },
      isReversal: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: false,
        field: 'is_reversal'
      },
      dateAt: {
        type: DataTypes.DATEONLY,
        allowNull: true,
        field: 'date_at',
        comment: 'Fecha ingresada por el usuario (fecha de ingreso/transferencia)'
      },
      createdAt: {
        type: DataTypes.DATE,
        field: 'created_at'
      }
    },
    {
      tableName: 'kardex',
      paranoid: false,
      timestamps: false,
      underscored: true
    }
  );

  Kardex.associate = function (models) {
    Kardex.belongsTo(models.Establishment, {
      foreignKey: 'establishment_id',
      as: 'establishment'
    });
    Kardex.belongsTo(models.InventoryProduct, {
      foreignKey: 'product_id',
      as: 'product'
    });
    Kardex.belongsTo(models.User, {
      foreignKey: 'user_id',
      as: 'user'
    });
    Kardex.belongsTo(models.Movement, {
      foreignKey: 'movement_id',
      as: 'movement'
    });
  };

  return Kardex;
}
